# Site settings
title: Warehouse UI
description: > # this means to ignore newlines until "baseurl:"
  UI redesign for Warehouse - to replace pypi
baseurl: "/warehouse-ui/" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
